---
- hosts: kube-master
  gather_facts: no
  tasks:
   - name: Copying helm
     copy:
       src: ~/cluster/helm
       dest: /usr/bin/
       mode: 0755
     become: yes
   
   - name: Initialize helm for future usage.
     raw: helm init --upgrade
     ignore_errors: true
     run_once: true
